version: '3.7'

services:

  yak-server:
    image: guardiandevelopment/yak-server:1.0.0.SNAPSHOT
    ports:
      - 9000:9000
      - 9001:9001
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 250M

  prom:
    image: prom/prometheus:v2.27.1
    ports:
      - 9090:9090
    volumes:
      - ./prom/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prom/rules.yml:/etc/prometheus/rules.yml
      - prometheus_data:/prometheus

  grafana:
    image: grafana/grafana:7.5.7
    ports:
      - 3000:3000
    volumes:
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/config.ini:/etc/grafana/config.ini
      - ./grafana/dashboards:/var/lib/grafana/dashboards

  node-exporter:
    image: prom/node-exporter
    ports:
      - 9100:9100
    networks:
      - default
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 100M

volumes:
  # store prom metrics between runs
  prometheus_data: {}

networks:
  default:
    name: metrics-network
